CREATE OR REPLACE PACKAGE Data_Validations AS

  FUNCTION Is_Email(email IN VARCHAR2) RETURN BOOLEAN;
  
  FUNCTION Is_AlphaNumeric(p_input_string IN VARCHAR2) RETURN BOOLEAN;
  
  FUNCTION Is_Date(p_date IN VARCHAR2, p_date_format IN VARCHAR2) RETURN BOOLEAN;
  
  FUNCTION Is_Alpha(p_string VARCHAR2) RETURN BOOLEAN;
  
  FUNCTION Is_Numeric(p_string VARCHAR2) RETURN BOOLEAN;
  
  FUNCTION Is_Country_Code(p_code VARCHAR2) RETURN BOOLEAN;
  
  FUNCTION Is_Currency_Code(p_code VARCHAR2) RETURN BOOLEAN;
  
  FUNCTION Is_UUID(p_uuid IN VARCHAR2) RETURN BOOLEAN;
  
  FUNCTION Is_JSON(p_json_string IN VARCHAR2) RETURN BOOLEAN;
  
  FUNCTION Is_XML(p_xml_string IN CLOB) RETURN BOOLEAN;
  
  FUNCTION Is_Hex_Color_Code(p_color_code IN VARCHAR2) RETURN BOOLEAN;

END Data_Validations;
/
